import uuid from 'uuid/v1';

export default [
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'REQUEST',
    amount: 30.5,
  },
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'REQUEST',
    amount: 30.5,
  },
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'APPROVED',
    amount: 30.5,
  },
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'REQUEST',
    amount: 30.5,
  },
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'REQUEST',
    amount: 30.5,
  },
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'REQUEST',
    amount: 30.5,
  },
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'REQUEST',
    amount: 30.5,
  },
  {
    linearId: uuid(),
    externalId: 'CDD1049',
    issuer: 'Central Bank',
    requester: 'BankA',
    requesterDate: '2020-01-01',
    currency: 'Moroccan DH',
    owner: 'BankA',
    type: 'PLEDGE',
    status: 'REQUEST',
    amount: 30.5,
  },

];
